Documentation fix AMonninger
econ-ark/HARK pull request #1174
Opened 2022-09-20 15:00 UTC by AMonninger

Transferring HARKmanual to Documentation.

To do:
- Needs reviewing
- Updating/Deleting HARKmanual in ../Documentation/_static

2022-09-22 15:29 UTC, aniecon commented on Documentation/contributing/CONTRIBUTING.md
> +Finally, if you write a new model module, the HARK team asks that you also provide a short mathematical writeup of the model as a PDF.  This document does not need to go into great detail about the s
'econ-arl' instead of 'econ-ark' in the ConsumptionSavingModels.pdf link.

2022-09-22 15:30 UTC, aniecon commented on Documentation/contributing/CONTRIBUTING.md
> +* The top of every module should begin with a ''docsting'' providing a clear description of the contents of the module.  The first sentence should concisely summarize the file, as it may appear in an
docstring*

2022-09-23 11:03 UTC, aniecon commented on Documentation/contributing/CONTRIBUTING.md
> +The HARK team wants the toolKit to be as accessible to users as possible; our greatest fear (Other than spiders, of course) is that a new user will open up our code, get hopelessly confused trying to
online documentation](https://econ-ark.github.io/HARK/) --- LINK BROKEN.

2022-09-23 11:15 UTC, aniecon requested changes
Hey Adrian, suggested some changes in the comments. Looks otherwise fine.
Ani

2022-09-30 16:53 UTC, AMonninger commented
> Hey Adrian, suggested some changes in the comments. Looks otherwise fine. Ani

Thank you Ani!

2022-10-19 18:28 UTC, merged